### ISSUE TITLE
Undefined $http_response_header variable

### ISSUE THREAD

**Issue by Archie22is** [benjihughes/php-InstagramFeed#1]
Hi there, 

Small issue on line 192. The var `$http_response_header` is undefine. Where does that have to be added? 
``Notice: Undefined variable: http_response_header in /inc/InstagramFeed.php on line 192
Couldn't get a feed for username: thedigitalocean`` – testing with Digital Ocean's account.

**Comment by benjihughes** [comment]
Hi there Archie,

`$http_response_header` is a global PHP array that's available once `file_get_contents()` has been called. 

You can read more about that here:
http://php.net/manual/en/reserved.variables.httpresponseheader.php

In your case, it seems that the call to `file_get_contents()` is what's failing, and since the `@` operator is used before it, it won't flag up any errors. I've used this since it's prone to throwing a lot of non-fatal warnings. 

Try removing the `@` operator before the call to see if you get any more information from that.
